name: tapris
services:
  bot:
    image: tapnisu/tapris
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      TAPRIS_TOKEN: ${TAPRIS_TOKEN}
      TAPRIS_DATABASE_URL: postgres://tapris:chisaki@db:5432/tapris?schema=public
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      POSTGRES_DB: tapris
      POSTGRES_USER: tapris
      POSTGRES_PASSWORD: chisaki
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true

volumes:
  db_data:
