name: tapris
services:
  bot:
    image: tapnisu/tapris
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      TAPRIS_TOKEN: ${TAPRIS_TOKEN}
      TAPRIS_DATABASE_URL: postgres://tapris:chisaki@db:5432/tapris?schema=public
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      POSTGRES_DB: tapris
      POSTGRES_USER: tapris
      POSTGRES_PASSWORD: chisaki
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
