version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: node:16
      
jobs:
  lint:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          yarn
          yarn lint
  build:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          yarn
          yarn build  

workflows:
  my-custom-workflow:
    jobs:
      - lint
      - build
