name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Packages install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Packages install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Lint
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint
